### ISSUE TITLE
How to change/update IoT Hub info on devkit after OOBE completed?

### ISSUE THREAD

**Issue by jseokkim** [microsoft/Azure-Percept-Private-Preview#187]
Hi,

I have completed devkit setup and OOBE to connect IoT hub.
But, for some reason, I have to change the IoT Hub to other instance.
Since SoftAP is not available any more, I can't restart OOBE to set the connection to IoT Hub.
Is there any way to restart SoftAP or just update IoT Hub directly on devkit?

**Comment by v-iskha** [comment]
@jseokkim - Check if you can SSH the device. If yes then
1. SSH to the device access point (10.1.1.1) 
2. Identify and copy the device ethernet IP address 
3. Connect to OOBE using the copied ethernet IP based URL

**Comment by jseokkim** [comment]
Hi,

Although I could connect to the DevKit via ssh root@<ip>, but I cannot connect to http://<ip> or https://<ip> from my desktop which was used to complete OOBE via SoftAP
Should I check web server or OOBE server is running on the devkit? If yes, how to check and restart?

Thanks,
Jaeseok
________________________________

**Comment by dankronstal** [comment]
Same issue for me - cannot connect to ethernet IP of device, http:// or https:// either port 80 or port 4242 (just trying everything). Device is up and running great, but I'd love to connect to new sub and hub. What's the play?

**Comment by v-iskha** [comment]
@jseokkim - Since you can SSH the devce, try below steps

[SSH into your devkit](https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/general/troubleshooting/ssh_and_serial_connection_setup.md) using “root” as the username. If you disabled the SSH “root” user login via OOBE, you must re-enable it. 
Run this command after successfully connecting:
mkdir -p /var/custom-configs/home; chmod 755 /var/custom-configs/home

To recover previous user home data, run the following command:
mkdir -p /tmp/prev-rootfs && mount /dev/mmcblk0p3 /tmp/prev-rootfs && [ ! -L /tmp/prev-rootfs/home ] && cp -a /tmp/prev-rootfs/home/* /var/custom-configs/home/. && echo "User home migrated!"; umount /tmp/prev-rootfs

**Comment by v-iskha** [comment]
@jseokkim @dankronstal - For changing the settings of IoT Hub, please refer [this](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-create-through-portal#change-the-settings-of-the-iot-hub) link.

**Comment by mikelor** [comment]
@jseokkim @dankronstal I believe the OOBE webpage stops working after 30 minutes. Try powering down the device, then restart it. After it's powered up, connect to the hotspot, and then try and reach the OOBE webpage.

**Comment by dankronstal** [comment]
@v-iskha thanks, but what i'm intending to do is more like a setting change on the Percept to say "now go talk to _that_ IoT Hub over in that _other_ azure subscription. Sounds like I'll just have to OOBE the thing again.

**Comment by v-iskha** [comment]
@dankronstal - Sure you can always run the OOBE whenever requirement changes :) Let me know the outcome.

**Comment by v-iskha** [comment]
@dankronstal - Any updates? Did running the OOBE again helped you.

**Comment by jseokkim** [comment]
Thanks for checking.

I could change IoT Hub by rerunning OOBE.

Thanks,
Jaeseok
________________________________

**Comment by v-iskha** [comment]
@jseokkim - Perfect. Thanks for confirming.
